name: Auto Build Spider Jar

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    permissions:
      contents: write

    steps:
      - name: 拉取代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 配置 JDK 17（必须 17！）
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: 编译 + 打包
        run: call buildAndGenJar.bat
        shell: cmd

      - name: 提交更新（永不冲突版）
        uses: EndBug/add-and-commit@v9
        with:
          message: "CI 自动更新 Jar"
          add: "jar/*.jar jar/*.md5"
          default_author: github_actions
          pull: "true"
