name: Auto Build Spider Jar

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    permissions:
      contents: write
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: 拉取代码（允许强制拉取最新）
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: 配置 JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: 执行打包
        run: |
          call gradlew.bat assembleRelease --no-daemon
          call jar\genJar.bat
        shell: cmd

      - name: 配置 Git（解决冲突核心）
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git pull origin main --rebase
        shell: cmd

      - name: 提交并推送（强制同步）
        uses: EndBug/add-and-commit@v9
        with:
          message: "CI 自动更新 Jar"
          add: "jar/*.jar jar/*.md5"
          push: "origin HEAD:main"
